language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly
notifications:
  email: false
# after_success:
#   - julia -e 'cd(Pkg.dir("LibArchive")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

cache:
  directories:
  - $HOME/.julia/artifacts
